# Generated by Django 6.0.2 on 2026-03-26 14:30

import movie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='emb',
            field=models.BinaryField(blank=True, default=movie.models.get_default_embedding),
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='movie/images/default.jpg', upload_to='movie/images/'),
        ),
    ]
